### ISSUE TITLE
Edit Tags in ContentRepository

### ISSUE THREAD

**Issue by okkevdeijk** [Geta/Tags#55]
First of all: we would like to say that we really appreciate the GetaTags plugin and all the work you did for it. However, we encountered a situation that the edit function in the admin control does only edit the tags in the _internal tagrepository_ and does not edit the tags in the _existing content_ of Episerver (the ContentRepository). Though this exactly the functionality one of our customers is looking for! 

We already worked on a working solution to search for the properties with the Tags attribute, create a writable clone of it and save the editted tag again. We suggest that you problably can implement this in a new update of the plugin. Can we/you maybe create a Fork where we can pull our code change so you can do a code review in it? 

Thanks so much in advance!

**Comment by frederikvig** [comment]
Hi! Absolutely, pull requests are always appreciated.

**Comment by okkevdeijk** [comment]
Hi Frederik! I tried making a pull request according to this [tutorial](https://services.github.com/on-demand/github-cli/open-pull-request-github). However I get a 403 error, acces denied. Do I need permission to make a pull request. Thanks!

**Comment by frederikvig** [comment]
Did you fork it first?

**Comment by okkevdeijk** [comment]
Thanks, succeeded now.

**Comment by patkleef** [comment]
Hi!

- We would prefer to have a checkbox so that the editor can choose if he wants to update all pages. Under GroupKey an extra line with a checkbox, see screenshot.
- If somebody updates the tag 'test2' to 'test2A' and a property contains multiple tags, e.g. test1,test2,test3 make sure that the order is not changed. Instead of doing this test1,test3,test2A -> test1,test2A,test3

![image](https://user-images.githubusercontent.com/2243586/35333566-7796535e-010f-11e8-8804-f3e8b2ad42fd.png)
